# Generated by Django 3.1.6 on 2021-02-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('descrition', models.TextField()),
                ('duration', models.IntegerField()),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
